'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4918
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SubtitleGen.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property add() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("add", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property add_12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add_12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property add_128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add_128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property add_18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add_18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property add_26() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add_26", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property error_128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("error_128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property error_26() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("error_26", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property errorRed() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("errorRed", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property help() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("help", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property help_128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("help_128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property help_26() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("help_26", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property info() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("info", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property info_26() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("info_26", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property info_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("info_48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property InfoTalk() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("InfoTalk", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property InfoTalk_128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("InfoTalk_128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property InfoTalk_26() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("InfoTalk_26", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property NavBack() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NavBack", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property NavForward() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NavForward", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ok() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ok", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property ok_12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ok_12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ok_128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ok_128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ok_18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ok_18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ok_26() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ok_26", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property openHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("openHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PreviewMode() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("PreviewMode", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property PreviewMode_128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PreviewMode_128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PreviewMode_26() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PreviewMode_26", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property saveHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("saveHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property substract() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("substract", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property substract_12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("substract_12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property substract_128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("substract_128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property substract_18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("substract_18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property substract_26() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("substract_26", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property txtBlank() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("txtBlank", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property txtBlank_12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("txtBlank_12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property txtBlank_128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("txtBlank_128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property txtBlank_18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("txtBlank_18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property txtBlank_26() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("txtBlank_26", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property txtNew() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("txtNew", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property txtNew_128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("txtNew_128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property txtNew_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("txtNew_256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property txtNew_26() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("txtNew_26", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property txtNew2() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("txtNew2", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property txtNew2_12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("txtNew2_12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property txtNew2_128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("txtNew2_128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property txtNew2_18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("txtNew2_18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property txtNew2_26() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("txtNew2_26", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property txtOpen() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("txtOpen", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property txtOpen_128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("txtOpen_128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property txtOpen_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("txtOpen_256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property txtOpen_26() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("txtOpen_26", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property txtOpen2() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("txtOpen2", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property txtOpen2_12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("txtOpen2_12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property txtOpen2_128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("txtOpen2_128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property txtOpen2_18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("txtOpen2_18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property txtOpen2_26() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("txtOpen2_26", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property txtSave() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("txtSave", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property txtSave_128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("txtSave_128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property txtSave_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("txtSave_256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property txtSave_26() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("txtSave_26", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property txtSave2() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("txtSave2", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property txtSave2_12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("txtSave2_12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property txtSave2_128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("txtSave2_128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property txtSave2_18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("txtSave2_18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property txtSave2_26() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("txtSave2_26", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property txtValidate() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("txtValidate", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property txtValidate_12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("txtValidate_12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property txtValidate_128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("txtValidate_128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property txtValidate_18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("txtValidate_18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property txtValidate_26() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("txtValidate_26", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property txtValidate2() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("txtValidate2", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property txtValidate2_12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("txtValidate2_12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property txtValidate2_128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("txtValidate2_128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property txtValidate2_18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("txtValidate2_18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property txtValidate2_26() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("txtValidate2_26", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Warning() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Warning", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property Warning_128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Warning_128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property x_12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x_12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property x_128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x_128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property x_18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x_18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property x_26() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x_26", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property x_copy() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("x_copy", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
    End Module
End Namespace
